[package]
name = "rmenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.1"
egui_extras = "0.24.2"
env_logger = "0.10.1"
freedesktop_entry_parser = "1.3.0"
shlex = "1.2.0"
